// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/mysza/paymentsapi/domain"
import mock "github.com/stretchr/testify/mock"

// PaymentsRepository is an autogenerated mock type for the PaymentsRepository type
type PaymentsRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *PaymentsRepository) Add(_a0 *domain.Payment) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*domain.Payment) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Payment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
